<?php
/**
 * This file is part of the phpCacheAdmin.
 * Copyright (c) Róbert Kelčák (https://kelcak.com/)
 */

declare(strict_types=1);

/*
 * Do not edit this file but copy it to config.php.
 */

return [
    /**
     * The order of the items also changes the position of the
     * sidebar links, the first item is also the default dashboard.
     *
     * You can comment out (or delete) any dashboard.
     */
    'dashboards'     => [
        RobiNN\Pca\Dashboards\Server\ServerDashboard::class,
        RobiNN\Pca\Dashboards\Redis\RedisDashboard::class,
        RobiNN\Pca\Dashboards\Memcached\MemcachedDashboard::class,
        RobiNN\Pca\Dashboards\OPCache\OPCacheDashboard::class,
        RobiNN\Pca\Dashboards\APCu\APCuDashboard::class,
        RobiNN\Pca\Dashboards\Realpath\RealpathDashboard::class,
    ],
    'redis'          => [
        [
            'name' => 'Localhost', // The server name (optional).
            'host' => '127.0.0.1', // Optional when a path or nodes is specified.
            /*'nodes' => [
                // List of cluster nodes.
                '127.0.0.1:7000',
                '127.0.0.1:7001',
                '127.0.0.1:7002',
            ],*/
            'port' => 6379, // Optional when the default port is used.
            //'scheme'    => 'tls', // Connection scheme (optional).
            /*'ssl'       => [
                // SSL options for TLS https://www.php.net/manual/en/context.ssl.php - requires Redis >= 6.0 (optional).
                'cafile'      => 'private.pem',
                'verify_peer' => true,
            ],*/
            //'database'  => 0, // Default database (optional).
            //'username'  => '', // ACL - requires Redis >= 6.0 (optional).
            //'password'  => '', // Optional.
            //'authfile'  => '/run/secrets/file_name', // File with a password, e.g., Docker secrets (optional).
            //'path'      => '/var/run/redis/redis-server.sock', // Unix domain socket (optional).
            //'databases' => 16, // Number of databases, use this if the CONFIG command is disabled (optional).
            //'scansize'  => 1000, // Number of keys, the server will use the SCAN command instead of KEYS (optional).
            //'separator' => ':', // Separator for tree view (optional)
        ],
    ],
    'memcached'      => [
        [
            'name' => 'Localhost', // The server name, optional.
            'host' => '127.0.0.1', // Optional when a path is specified.
            'port' => 11211, // Optional when the default port is used.
            //'path' => '/var/run/memcached/memcached.sock', // Unix domain socket (optional).
            //'separator' => ':', // Separator for tree view (optional)
        ],
    ],
    'apcuseparator' => ':', // Separator for tree view (optional)
    // Example of authentication with http auth.
    /*'auth'           => static function (): void {
        $username = 'admin';
        $password = 'pass';

        if (isset($_GET['logout'])) {
            setcookie('auth_reset', '1', time() + 60, '/');

            $clean_uri = strtok($_SERVER['REQUEST_URI'], '?');
            $is_https = (
                (isset($_SERVER['HTTPS']) && ($_SERVER['HTTPS'] === 'on' || $_SERVER['HTTPS'] === 1)) ||
                (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')
            );

            header('Location: http'.($is_https ? 's' : '').'://'.$_SERVER['HTTP_HOST'].$clean_uri);
            exit;
        }

        if (isset($_COOKIE['auth_reset'])) {
            setcookie('auth_reset', '', time() - 3600, '/');

            header('WWW-Authenticate: Basic realm="phpCacheAdmin Login"');
            header('HTTP/1.0 401 Unauthorized');
            exit('You have been logged out.');
        }

        if (
            !isset($_SERVER['PHP_AUTH_USER'], $_SERVER['PHP_AUTH_PW']) ||
            $_SERVER['PHP_AUTH_USER'] !== $username || $_SERVER['PHP_AUTH_PW'] !== $password
        ) {
            header('WWW-Authenticate: Basic realm="phpCacheAdmin Login"');
            header('HTTP/1.0 401 Unauthorized');
            exit('Incorrect username or password!');
        }
    },*/
    // Decoding / Encoding functions
    'converters'     => [
        'gzcompress' => [
            'view' => static fn (string $value): ?string => @gzuncompress($value) !== false ? gzuncompress($value) : null,
            'save' => static fn (string $value): string => gzcompress($value),
        ],
        'gzencode'   => [
            'view' => static fn (string $value): ?string => @gzdecode($value) !== false ? gzdecode($value) : null,
            'save' => static fn (string $value): string => gzencode($value),
        ],
        'gzdeflate'  => [
            'view' => static fn (string $value): ?string => @gzinflate($value) !== false ? gzinflate($value) : null,
            'save' => static fn (string $value): string => gzdeflate($value),
        ],
        'zlib'       => [
            'view' => static fn (string $value): ?string => @zlib_decode($value) !== false ? zlib_decode($value) : null,
            'save' => static fn (string $value): string => zlib_encode($value, ZLIB_ENCODING_DEFLATE),
        ],
        /*'gz_magento' => [
            'view' => static function (string $value): ?string {
                $prefix = ':gz:';
                $value = str_starts_with($value, $prefix) ? substr($value, strlen($prefix)) : $value;

                return @gzuncompress($value) !== false ? gzuncompress($value) : null;
            },
            'save' => static fn (string $value): string => ':gz:'.gzcompress($value),
        ],*/
    ],
    // Formatting functions, it runs after decoding
    'formatters'     => [
        'unserialize' => static function (string $value): ?string {
            $unserialized_value = @unserialize($value, ['allowed_classes' => false]);
            if ($unserialized_value !== false && is_array($unserialized_value)) {
                try {
                    return json_encode($unserialized_value, JSON_THROW_ON_ERROR);
                } catch (JsonException) {
                    return null;
                }
            }

            return null;
        },
    ],
    // Customizations
    //'timezone'       => 'Europe/Bratislava', // Leave empty (or commented out) to get it automatically obtained.
    'timeformat'     => 'd. m. Y H:i:s',
    'decimalsep'     => ',',
    'thousandssep'   => ' ',
    'listview'       => 'table', // table/tree - default key list view
    'panelrefresh'   => 30, // In seconds, refresh interval for panels - default 30
    'metricsrefresh' => 60, // In seconds, refresh interval for metrics - default 60
    'metricstab'     => 1440, // Default tab in metrics, 60 - Last hour, 1440 - Last day, 10080 - Last week, 43200 - Last month - default 1440
    'hash'           => 'pca', // Any random string to secure a metrics DB file.
    'metricsdir'     => __DIR__.'/tmp/metrics', // Directory for metrics DB files.
    'twigcache'      => __DIR__.'/tmp/twig', // Directory for Twig cache files.
    //'pcapath'        => 'vendor/robinn/phpcacheadmin/', // Path to the package when installed via composer. Used for assets.
    //'url'            => '/', // URL to the dashboard when installed via composer, e.g., /phpcacheadmin
];
