services:
  phpcacheadmin:
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
#    volumes:
#      # If you want to use config.php instead of ENV variables
#      - "./config.php:/app/config.php"
    environment:
      - PCA_REDIS_0_HOST=redis
      - PCA_REDIS_0_PORT=6379
      - PCA_MEMCACHED_0_HOST=memcached
      - PCA_MEMCACHED_0_PORT=11211
    ports:
      - "8080:80"

  redis:
    image: redis:7-alpine
  memcached:
    image: memcached:1-alpine
