name: Close PR

on:
  pull_request_target:
    types:
      - opened

jobs:
  close_pull_request:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Comment on and close PR
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `
              Thank you for your contribution!
              This repository does not accept pull requests, as changes are managed directly by the maintainer.
              If you’d like to suggest improvements or report issues, please open an issue instead.
              In rare cases, a maintainer may reopen this pull request if the change is considered valuable.
            `;

            const pr_number = context.issue.number;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: comment
            });

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              state: 'closed'
            });
