name: Build Production Docker Images

on:
  push:
    branches: [ master ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

#      - name: Login to DockerHub
#        uses: docker/login-action@v3
#        with:
#          username: robinn
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./docker/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ steps.prepare-build-env-variables.outputs.BUILD_DATE }}
          tags: |
#            robinn/phpcacheadmin:${{ github.ref_name }}
#            robinn/phpcacheadmin:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
          push: true
          labels: |
            org.opencontainers.image.title="${{ github.event.repository.name }}"
            org.opencontainers.image.description="${{ github.event.repository.description }}"
            org.opencontainers.image.authors="${{ github.event.repository.html_url }}"
            org.opencontainers.image.url="https://github.com/${{ github.repository }}"
            org.opencontainers.image.source="https://github.com/${{ github.repository }}"
            org.opencontainers.image.vendor="${{ github.event.repository.owner.login }}"