name: Build Production Docker Images

on:
  push:
    branches: [ master ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  RELEASE_VERSION: v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: robinn
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Prepare build metadata
        id: build-metadata
        run: |
          # Fail on errors and undefined variables
          set -euo pipefail
          TIMESTAMP_TZ_UTC=$(date -u +'%Y-%m-%d %H:%M:%S (%Z)')
          echo "TIMESTAMP_TZ_UTC=${TIMESTAMP_TZ_UTC}" >> ${GITHUB_OUTPUT}
          
          # Log metadata for debugging
          echo -e "\nGenerated execution metadata:"
          echo "  - TIMESTAMP_TZ_UTC=${TIMESTAMP_TZ_UTC}"

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./docker/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ steps.build-metadata.outputs.TIMESTAMP_TZ_UTC }}
          tags: |
            robinn/phpcacheadmin:{{ env.RELEASE_VERSION }}
            robinn/phpcacheadmin:latest
            ghcr.io/robinn1/phpcacheadmin:{{ env.RELEASE_VERSION }}
            ghcr.io/robinn1/phpcacheadmin:latest
          push: true
          labels: |
            org.opencontainers.image.title="${{ github.event.repository.name }}"
            org.opencontainers.image.description="${{ github.event.repository.description }}"
            org.opencontainers.image.authors="${{ github.event.repository.html_url }}"
            org.opencontainers.image.url="https://github.com/${{ github.repository }}"
            org.opencontainers.image.source="https://github.com/${{ github.repository }}"
            org.opencontainers.image.vendor="${{ github.event.repository.owner.login }}"